# Site settings
baseURL = "https://example.com"
languageCode = "en-US"
title = "Config.toml Title Test"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2022 Config.toml Copyright Name Test"

[params]

  # Metadata for search engines and social sharing
  author = "Jenny Jones"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/PXL_20220605_004304191.jpg"
      position = "top"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Pellentesque"

      [[params.links.list1.link]]
        text = "luctus-urna TEST"
        url = "luctus-urna.html"

      [[params.links.list1.link]]
        text = "ac diam"
        url = "#"

      [[params.links.list1.link]]
        text = "feugiat posuere"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Nam"

      [[params.links.list2.link]]
        text = "non nunc id"
        url = "#"

      [[params.links.list2.link]]
        text = "tortor scelerisque"
        url = "#"

      [[params.links.list2.link]]
        text = "ultrices"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Aliquam"

      [[params.links.list3.link]]
        text = "venenatis felis"
        url = "#"

      [[params.links.list3.link]]
        text = "quis convallis"
        url = "#"

      [[params.links.list3.link]]
        text = "commodo"
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
